// Node smoke test for the framewright WASM module.
//
// Usage: node wasm/test/smoke.mjs <hdr10_matrix.mp4>
// The fixture is the solid RGB (208, 64, 32) BT.2020+PQ file generated by the
// CMake test-fixture machinery (build/test_fixtures/hdr10_matrix.mp4).

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const fixture = process.argv[2];
if (!fixture) {
  console.error("usage: node smoke.mjs <hdr10_matrix.mp4>");
  process.exit(2);
}

const { default: createFramewright } = await import(
  join(here, "..", "dist", "framewright.js")
);
const M = await createFramewright();

let failures = 0;
function check(name, cond, detail = "") {
  if (cond) {
    console.log(`ok: ${name}`);
  } else {
    console.error(`FAIL: ${name} ${detail}`);
    failures++;
  }
}

M.FS.writeFile("/in.mp4", readFileSync(fixture));

// --- Metadata + passthrough decode (BT.2020 matrix) ------------------------
{
  const r = new M.VideoReader();
  check("open", r.open("/in.mp4", false, false, false));
  check("dimensions", r.width() === 192 && r.height() === 108,
        `${r.width()}x${r.height()}`);
  check("colorSpace tag", r.colorSpace() === "bt2020nc", r.colorSpace());
  check("colorTransfer tag", r.colorTransfer() === "smpte2084", r.colorTransfer());

  const f = r.read();
  check("read returns Uint8Array", f instanceof Uint8Array && f.length === 192 * 108 * 3);
  const c = (54 * 192 + 96) * 3;
  // Solid RGB (208, 64, 32) in BGR order; BT.709/601 decode would be ~7 off.
  check("passthrough B", Math.abs(f[c + 0] - 32) <= 3, `${f[c + 0]}`);
  check("passthrough G", Math.abs(f[c + 1] - 64) <= 3, `${f[c + 1]}`);
  check("passthrough R", Math.abs(f[c + 2] - 208) <= 3, `${f[c + 2]}`);
  r.close();
  r.delete();
}

// --- readRGBA: canvas-ready output -----------------------------------------
{
  const r = new M.VideoReader();
  r.open("/in.mp4", false, false, false);
  const f = r.readRGBA();
  check("readRGBA returns Uint8ClampedArray",
        f instanceof Uint8ClampedArray && f.length === 192 * 108 * 4);
  const c = (54 * 192 + 96) * 4;
  // RGBA order with alpha 255; same values as the BGR passthrough read.
  check("readRGBA R", Math.abs(f[c + 0] - 208) <= 3, `${f[c + 0]}`);
  check("readRGBA G", Math.abs(f[c + 1] - 64) <= 3, `${f[c + 1]}`);
  check("readRGBA B", Math.abs(f[c + 2] - 32) <= 3, `${f[c + 2]}`);
  check("readRGBA alpha", f[c + 3] === 255);
  r.close();
  r.delete();
}

// --- read16: code values at full precision ---------------------------------
{
  const r = new M.VideoReader();
  r.open("/in.mp4", false, false, false);
  const f = r.read16();
  check("read16 returns Uint16Array", f instanceof Uint16Array);
  const c = (54 * 192 + 96) * 3;
  check("read16 B", Math.abs(f[c + 0] - 32 * 257) <= 3 * 257, `${f[c + 0]}`);
  check("read16 G", Math.abs(f[c + 1] - 64 * 257) <= 3 * 257, `${f[c + 1]}`);
  check("read16 R", Math.abs(f[c + 2] - 208 * 257) <= 3 * 257, `${f[c + 2]}`);
  r.close();
  r.delete();
}

// --- readLinear: PQ removed, linear light ----------------------------------
{
  const r = new M.VideoReader();
  r.open("/in.mp4", false, false, false);
  const f = r.readLinear();
  check("readLinear returns Float32Array", f instanceof Float32Array);
  const c = (54 * 192 + 96) * 3;
  // PQ code 208/255 is ~1800 nits: linear red far exceeds SDR white (1.0).
  check("linear R > 1 (HDR highlight)", f[c + 2] > 1.0, `${f[c + 2]}`);
  check("linear ordering B < G < R", f[c + 0] < f[c + 1] && f[c + 1] < f[c + 2]);
  r.close();
  r.delete();
}

// --- Tone-mapped SDR read ---------------------------------------------------
{
  const r = new M.VideoReader();
  r.open("/in.mp4", false, false, true);
  check("toneMappingActive", r.toneMappingActive());
  const f = r.read();
  check("tone-mapped read works", f instanceof Uint8Array);
  r.close();
  r.delete();
}

// --- FFV1 write round-trip --------------------------------------------------
{
  const w = new M.VideoWriter();
  check("writer openFfv1", w.openFfv1("/out.mkv", 64, 48, 30, 1));
  const frame = new Uint8Array(64 * 48 * 3);
  for (let i = 0; i < frame.length; i += 3) {
    frame[i] = 200; frame[i + 1] = 100; frame[i + 2] = 50;
  }
  check("writer write", w.write(frame));
  w.release();
  w.delete();

  const r = new M.VideoReader();
  check("reopen FFV1 output", r.open("/out.mkv", false, false, false));
  const back = r.read();
  check("FFV1 round-trip exact",
        back && back[0] === 200 && back[1] === 100 && back[2] === 50,
        back ? `${back[0]},${back[1]},${back[2]}` : "null");
  r.close();
  r.delete();
}

console.log(failures === 0 ? "\nALL SMOKE TESTS PASSED" : `\n${failures} FAILURES`);
process.exit(failures === 0 ? 0 : 1);
